# Generated by Django 3.2.7 on 2021-09-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('sizetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='soccershop.sizetype')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='syzetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='soccershop.sizetype'),
        ),
    ]
